BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Motherbord" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Socket"	TEXT NOT NULL,
	"Chipset"	TEXT NOT NULL,
	"Format"	TEXT NOT NULL,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CPUs" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Socket"	TEXT NOT NULL,
	"Base_Speed"	NUMERIC NOT NULL,
	"Boost_Speed"	NUMERIC,
	"Cores"	INTEGER NOT NULL,
	"Threads"	TEXT,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PC_Cases" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Format"	TEXT NOT NULL,
	"Location"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PSUs" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Power"	INTEGER NOT NULL,
	"Format"	TEXT,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Coolers" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT,
	"Sockets"	TEXT,
	"Location"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "HDDs" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Connector"	TEXT NOT NULL,
	"Storage"	TEXT NOT NULL,
	"RPM"	NUMERIC,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SSDs" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Storage"	INTEGER NOT NULL,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Expension_Cards" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Type"	TEXT NOT NULL,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Routers" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Switches" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Location"	TEXT,
	"Comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
